### ISSUE TITLE
Create postman collection for api endpoints

### ISSUE THREAD

**Issue by ihakkitekin** [Trendyol/codex#145]

**Comment by ddenizakpinar** [comment]
We might want to reconsider this since we are planning to build an admin dashboard for our endpoints

**Comment by ddenizakpinar** [comment]
> We might want to reconsider this since we are planning to build an admin dashboard for our endpoints

Do we still need this? @kayraberktuncer

**Comment by kayraberktuncer** [comment]
I don't think we need.
