### ISSUE TITLE
Article & Discussion Backend Implementation

### ISSUE THREAD

**Issue by BerkinAKKAYA** [Trendyol/codex#183]
- [ ] An 'Article' entity will be created
- [ ] Create endpoints for Article, Discussion and Comment

Endpoints: List, Get, Create, Update, Delete, Comment, Like

```
// Draft Article Entity:
export class ArticleEntity {
  readonly userId: string;
  readonly title: string;
  readonly content: string;

  readonly isApproved: boolean; // article için false, discuss ve comment için true
  readonly isPublished: boolean; // article ve discuss için false, comment için true
  readonly problemId?: string;

  readonly parentId?: string;
  readonly depth: number;

  readonly likedBy: string[];
}
```

**Comment by ddenizakpinar** [comment]
Codex currently does not support pagination any of its endpoints. I feel like we should start to supporting it since we're building the articles section. We'll definitely need the pagination here. 
Could you create an issue to implement it after you complete this section?
